name: release

on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Post to Discord
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.discord_webhook }}
          DISCORD_EMBEDS: '[{"title":"${{ github.event.release.tag_name }}","url":"${{ github.event.release.html_url }}"}]'
        with:
          args: 'New version released!'
